cartpole1:
  env_id: CartPole-v1
  replay_memory_size: 100000
  batch_size: 32
  epsilon_init: 1.0
  epsilon_min: 0.05
  epsilon_decay: 0.9995
  network_sync_rate: 10
  gamma: 0.99
  learning_rate: 0.001
  stop_on_reward: 100000
  fc1_nodes: 10

cartpole2:
  env_id: CartPole-v1
  replay_memory_size: 100000
  batch_size: 32
  epsilon_init: 1.0
  epsilon_min: 0.05
  epsilon_decay: 0.99995
  network_sync_rate: 10
  gamma: 0.99
  learning_rate: 0.001
  stop_on_reward: 100000
  fc1_nodes: 10


flappybird1:
  env_id: FlappyBird-v0
  replay_memory_size: 100000
  batch_size: 32
  epsilon_init: 1.0
  epsilon_min: 0.05
  epsilon_decay: 0.99_995
  network_sync_rate: 10
  gamma: 0.99
  learning_rate: 0.0001
  stop_on_reward: 100000
  fc1_nodes: 512
  env_makee_params:
    use_lidar: False

